# Generated by Django 4.0.3 on 2022-04-12 02:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('ANDROID', 'ANDROID'), ('FULLSTACK', 'FULLSTACK')], default=0, max_length=9)),
                ('project_landingpage', cloudinary.models.CloudinaryField(default='image.jpg', max_length=255, verbose_name='image')),
                ('project_description', models.TextField()),
                ('project_owner', models.CharField(max_length=100)),
                ('project_member1', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member2', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member3', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member4', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member5', models.CharField(blank=True, max_length=50, null=True)),
                ('project_member6', models.CharField(blank=True, max_length=50, null=True)),
                ('github_link', models.URLField(max_length=100)),
            ],
        ),
    ]
