# Generated by Django 4.0.3 on 2022-04-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
