# Generated by Django 4.0.3 on 2022-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_project_id_project_projectid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ProjectId',
        ),
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
